# Generated by Django 5.2.7 on 2026-03-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weathericons',
            name='description',
        ),
        migrations.AlterField(
            model_name='weathericons',
            name='icon_file',
            field=models.ImageField(upload_to='static/weather_icons/'),
        ),
    ]
