# Generated by Django 5.2.7 on 2026-03-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_remove_weathericons_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathericons',
            name='icon_file',
            field=models.FileField(upload_to='static/weather_icons/'),
        ),
    ]
