# Generated by Django 5.2.7 on 2026-05-27 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_alter_weathericons_icon_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_icons', to='observations.weathericons')),
                ('icon_night', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='night_icons', to='observations.weathericons')),
            ],
            options={
                'verbose_name_plural': 'Weather Codes',
                'ordering': ['code'],
            },
        ),
    ]
