# Generated by Django 5.2.7 on 2026-07-23 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "system_core",
            "0008_rename_officelocationplacement_officelocation",
        ),
        (
            "users",
            "0001_initial",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="userprofile",
                    name="office_location",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="system_core.officelocation",
                    ),
                ),
                migrations.AlterField(
                    model_name="userprofile",
                    name="department",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="system_core.departmentsection",
                    ),
                ),
            ],
        ),
    ]