# Generated by Django 5.2.7 on 2026-07-23 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_office_location_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name="userprofile",
                    name="avatar",
                ),
            ],
        ),
    ]
