# Generated by Django 5.2.7 on 2026-07-23 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_avatar_alter_userprofile_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
    ]
