# Generated by Django 5.2.7 on 2026-08-06 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_employee_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
    ]
