# Generated by Django 5.2.7 on 2026-08-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='has_user_account',
            field=models.BooleanField(default=False),
        ),
    ]
