# Generated by Django 5.2.7 on 2026-01-13 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0041_remove_pestriskentrymainlisting_commodity_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadarImages',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_title', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=50)),
                ('published_date', models.DateTimeField(auto_now=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pestriskentrydetails',
            name='pest_risk_listing_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pest_risk_entries', to='agro.pestriskentrymainlisting'),
            preserve_default=False,
        ),
    ]
