# Generated by Django 5.2.7 on 2026-01-13 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0042_radarimages_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RadarImages',
        ),
    ]
