# Generated by Django 5.2.7 on 2026-01-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0043_delete_radarimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='pestriskentrymainlisting',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
