# Generated by Django 5.2.7 on 2026-02-03 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0044_pestriskentrymainlisting_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commoditycategory',
            options={'verbose_name': 'Sector', 'verbose_name_plural': 'Sectors'},
        ),
        migrations.AlterModelOptions(
            name='commoditytype',
            options={'verbose_name': 'Commodity Type', 'verbose_name_plural': 'Commodity Types'},
        ),
        migrations.AlterModelOptions(
            name='droughtalertlevel',
            options={'verbose_name': 'Drought Alert Level', 'verbose_name_plural': 'Drought Alert Levels'},
        ),
        migrations.AlterModelOptions(
            name='months',
            options={'verbose_name': 'Month', 'verbose_name_plural': 'Months'},
        ),
        migrations.AlterModelOptions(
            name='pestalertlevel',
            options={'verbose_name': 'Pest Alert Level', 'verbose_name_plural': 'Pest Alert Levels'},
        ),
        migrations.AlterModelOptions(
            name='pestriskaction',
            options={'verbose_name': 'Pest Risk Action', 'verbose_name_plural': 'Pest Risk Actions'},
        ),
        migrations.AlterModelOptions(
            name='pestriskeffect',
            options={'verbose_name': 'Pest Risk Effect', 'verbose_name_plural': 'Pest Risk Effects'},
        ),
        migrations.AlterModelOptions(
            name='pestriskentrydetails',
            options={'verbose_name': 'Pest Risk Detail', 'verbose_name_plural': 'Pest Risk Details'},
        ),
        migrations.AlterModelOptions(
            name='pestriskentrymainlisting',
            options={'verbose_name': 'Pest Risk Entry', 'verbose_name_plural': 'Pest Risk Entries'},
        ),
    ]
