# Generated by Django 5.2.7 on 2026-02-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0045_alter_commoditycategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pestriskaction',
            name='action_description',
            field=models.TextField(),
        ),
    ]
