# Generated by Django 5.2.7 on 2026-02-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0046_alter_pestriskaction_action_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pestriskeffect',
            name='effect_description',
            field=models.TextField(),
        ),
    ]
