# Generated by Django 5.2.7 on 2026-02-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0047_alter_pestriskeffect_effect_description'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pestriskentrymainlisting',
            constraint=models.UniqueConstraint(fields=('months', 'year', 'commodity'), name='unique_months_year_commodity'),
        ),
    ]
