# Generated by Django 5.2.7 on 2026-02-19 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0048_pestriskentrymainlisting_unique_months_year_commodity'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pestriskentrymainlisting',
            name='unique_months_year_commodity',
        ),
    ]
