# Generated by Django 5.2.7 on 2026-07-23 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0049_remove_pestriskentrymainlisting_unique_months_year_commodity'),
        ('system_core', '0006_sectors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommodityCategory',
            new_name='Sector',
        ),
        migrations.RemoveField(
            model_name='district',
            name='zone_id',
        ),
        migrations.AlterField(
            model_name='pestriskentrydetails',
            name='district_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system_core.district'),
        ),
        migrations.DeleteModel(
            name='Months',
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
