# Generated by Django 5.2.7 on 2026-07-23 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0050_rename_commoditycategory_sector_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommodityType',
            new_name='Commodity',
        ),
    ]
