# Generated by Django 5.2.7 on 2026-07-23 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0051_rename_commoditytype_commodity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commodity',
            old_name='commodity_category',
            new_name='sector',
        ),
    ]
