# Generated by Django 5.2.7 on 2026-07-23 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0052_rename_commodity_category_commodity_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sector', to='agro.sector'),
        ),
    ]
