# Generated by Django 5.2.7 on 2026-07-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0054_pestrisk'),
    ]

    operations = [
        migrations.AddField(
            model_name='pestrisk',
            name='months',
            field=models.JSONField(null=True),
        ),
    ]
