# Generated by Django 5.2.7 on 2026-07-30 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0055_pestrisk_months'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pestriskentrydetails',
            name='pest_risk_listing_id',
        ),
        migrations.AddField(
            model_name='pestriskentrydetails',
            name='commodity_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.commodity'),
        ),
        migrations.AddField(
            model_name='pestriskentrydetails',
            name='pest_risk_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pest_risk', to='agro.pestrisk'),
            preserve_default=False,
        ),
    ]
