# Generated by Django 5.2.7 on 2026-07-30 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0056_remove_pestriskentrydetails_pest_risk_listing_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pestriskentrydetails',
            name='commodity_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pr_commodity', to='agro.commodity'),
        ),
    ]
