# Generated by Django 5.2.7 on 2026-07-30 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0057_alter_pestriskentrydetails_commodity_id'),
        ('system_core', '0010_remove_officelocation_building_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pestriskentrydetails',
            name='pest_risk_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pest_risk', to='system_core.alertlevel'),
        ),
    ]
