# Generated by Django 5.2.7 on 2026-07-30 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0058_alter_pestriskentrydetails_pest_risk_id'),
        ('system_core', '0010_remove_officelocation_building_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pestriskentrydetails',
            name='pest_alert_lvl_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system_core.alertlevel'),
        ),
        migrations.AlterField(
            model_name='pestriskentrydetails',
            name='pest_risk_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pest_risk', to='agro.pestrisk'),
        ),
    ]
