# Generated by Django 5.2.7 on 2026-07-30 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0059_alter_pestriskentrydetails_pest_alert_lvl_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pestrisk',
            name='published_date',
        ),
    ]
