# Generated by Django 5.2.7 on 2026-07-31 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0060_remove_pestrisk_published_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pestriskentrydetails',
            name='published_date',
        ),
        migrations.AddField(
            model_name='pestriskentrydetails',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pestriskentrydetails',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pest_risk_item_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
