# Generated by Django 5.2.7 on 2026-07-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0061_remove_pestriskentrydetails_published_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pestriskentrydetails',
            name='info',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
