# Generated by Django 5.2.7 on 2026-07-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0062_alter_pestriskentrydetails_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pestriskentrydetails',
            name='info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
