# Generated by Django 5.2.7 on 2026-07-31 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0063_alter_pestriskentrydetails_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pestriskentrydetails',
            name='pest_risk_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pest_risk_entries', to='agro.pestrisk'),
        ),
    ]
