# Generated by Django 5.2.7 on 2026-08-14 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0064_alter_pestriskentrydetails_pest_risk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pestriskeffect',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pest_risk_effect_category', to='agro.sector'),
        ),
    ]
