# Generated by Django 5.2.7 on 2026-08-14 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0065_pestriskeffect_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='pestriskaction',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pest_risk_actions_category', to='agro.sector'),
        ),
    ]
