# Generated by Django 5.2.7 on 2026-08-14 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0066_pestriskaction_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='PestRiskInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('info_description', models.TextField()),
                ('published_date', models.DateTimeField(auto_now=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pest_risk_info_category', to='agro.sector')),
            ],
            options={
                'verbose_name': 'Pest Risk Info',
                'verbose_name_plural': 'Pest Risk Info',
            },
        ),
    ]
