# Generated by Django 5.2.7 on 2026-08-14 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0067_pestriskinfo'),
        ('system_core', '0010_remove_officelocation_building_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pestriskentrydetails',
            name='actions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.pestriskaction'),
        ),
        migrations.AlterField(
            model_name='pestriskentrydetails',
            name='drought_alert_lvl_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.droughtalertlevel'),
        ),
        migrations.AlterField(
            model_name='pestriskentrydetails',
            name='effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.pestriskeffect'),
        ),
        migrations.AlterField(
            model_name='pestriskentrydetails',
            name='info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.pestriskinfo'),
        ),
        migrations.AlterField(
            model_name='pestriskentrydetails',
            name='pest_alert_lvl_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system_core.alertlevel'),
        ),
        migrations.AlterField(
            model_name='pestriskentrydetails',
            name='precip_max',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='pestriskentrydetails',
            name='precip_min',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='pestriskentrydetails',
            name='temp_max',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pestriskentrydetails',
            name='temp_min',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
