# Generated by Django 5.2.7 on 2026-08-17 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0068_alter_pestriskentrydetails_actions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pestriskaction',
            name='commodity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pest_risk_actions_commodity', to='agro.commodity'),
        ),
        migrations.AddField(
            model_name='pestriskeffect',
            name='commodity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pest_risk_effect_commodity', to='agro.commodity'),
        ),
        migrations.AddField(
            model_name='pestriskinfo',
            name='commodity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pest_risk_info_commodity', to='agro.commodity'),
        ),
    ]
