# Generated by Django 5.2.7 on 2026-08-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0069_pestriskaction_commodity_pestriskeffect_commodity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pestriskaction',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='pestriskeffect',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='pestriskinfo',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='pestriskentrydetails',
            name='actions',
        ),
        migrations.RemoveField(
            model_name='pestriskentrydetails',
            name='effect',
        ),
        migrations.RemoveField(
            model_name='pestriskentrydetails',
            name='info',
        ),
        migrations.AddField(
            model_name='pestriskentrydetails',
            name='actions',
            field=models.ManyToManyField(blank=True, to='agro.pestriskaction'),
        ),
        migrations.AddField(
            model_name='pestriskentrydetails',
            name='effect',
            field=models.ManyToManyField(blank=True, to='agro.pestriskeffect'),
        ),
        migrations.AddField(
            model_name='pestriskentrydetails',
            name='info',
            field=models.ManyToManyField(blank=True, to='agro.pestriskinfo'),
        ),
    ]
