# Generated by Django 5.2.7 on 2026-08-18 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0070_remove_pestriskaction_sector_and_more'),
        ('system_core', '0010_remove_officelocation_building_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = []
