# Generated by Django 5.2.7 on 2026-08-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0071_pestriskentrydetails_unique_commodity_info_description'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pestriskinfo',
            constraint=models.UniqueConstraint(fields=('commodity', 'info_description'), name='unique_commodity_info_description'),
        ),
    ]
