# Generated by Django 5.2.7 on 2026-08-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0072_remove_pestriskentrydetails_unique_commodity_info_description_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pestriskeffect',
            constraint=models.UniqueConstraint(fields=('commodity', 'effect_description'), name='unique_commodity_effect_description'),
        ),
    ]
