# Generated by Django 5.2.7 on 2026-09-03 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0073_pestriskeffect_unique_commodity_effect_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commodity',
            options={'verbose_name': 'Commodity', 'verbose_name_plural': 'Commodities'},
        ),
    ]
