# Generated by Django 5.2.7 on 2026-01-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadarImages',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_title', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=50)),
                ('published_date', models.DateTimeField(auto_now=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
