# Generated by Django 5.2.7 on 2026-01-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radarimages',
            name='image_url',
            field=models.CharField(max_length=500),
        ),
    ]
