# Generated by Django 5.2.7 on 2026-01-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0002_alter_radarimages_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='radarimages',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
