# Generated by Django 5.2.7 on 2026-01-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0003_radarimages_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='radarimages',
            name='web_directory',
            field=models.CharField(default='/images/radar-images/', max_length=500),
        ),
    ]
