# Generated by Django 5.2.7 on 2026-01-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0004_radarimages_web_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radarimages',
            name='web_directory',
            field=models.CharField(default='/images/radar/', max_length=500),
        ),
    ]
