# Generated by Django 5.2.7 on 2026-02-03 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0005_alter_radarimages_web_directory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='radarimages',
            options={'verbose_name': 'Radar Image', 'verbose_name_plural': 'Radar Images'},
        ),
    ]
