# Generated by Django 5.2.7 on 2026-05-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0002_districtforecastdetails_temp_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtforecastdetails',
            name='max_precip',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='districtforecastdetails',
            name='weather_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
