# Generated by Django 5.2.7 on 2026-05-11 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0003_districtforecastdetails_max_precip_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='districtforecastdetails',
            old_name='max_precip',
            new_name='precip_max',
        ),
    ]
