# Generated by Django 5.2.7 on 2026-05-12 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0005_alertlevel_alter_probability_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtforecastdetails',
            name='prob_temp_max',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forecasts.alertlevel'),
        ),
    ]
