# Generated by Django 5.2.7 on 2026-05-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0007_districtforecastinstructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtforecastinstructions',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
