# Generated by Django 5.2.7 on 2026-05-18 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0009_rename_winds_districtforecastdetails_winds_max_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='districtforecast',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_forecasts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='districtforecast',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_forecasts_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='districtforecastdetails',
            name='forecast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_forecast_details', to='forecasts.districtforecast'),
        ),
    ]
