# Generated by Django 5.2.7 on 2026-05-20 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0011_districtforecastdetails_risk_precip_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtforecastdetails',
            name='risk_precip_max',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_precip_max', to='forecasts.risklevel'),
        ),
        migrations.AlterField(
            model_name='districtforecastdetails',
            name='risk_temp_max',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_temp_max', to='forecasts.risklevel'),
        ),
        migrations.AlterField(
            model_name='districtforecastdetails',
            name='risk_temp_min',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_temp_min', to='forecasts.risklevel'),
        ),
        migrations.AlterField(
            model_name='districtforecastdetails',
            name='risk_weather_conditions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_weather_conditions', to='forecasts.risklevel'),
        ),
        migrations.AlterField(
            model_name='districtforecastdetails',
            name='risk_winds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_winds', to='forecasts.risklevel'),
        ),
    ]
