# Generated by Django 5.2.7 on 2026-05-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0013_alter_districtforecastdetails_winds_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtforecastdetails',
            name='temp_max',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='districtforecastdetails',
            name='temp_min',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
    ]
