# Generated by Django 5.2.7 on 2026-05-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0015_alter_districtforecastdetails_precip_max'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="districtforecastdetails",
            constraint=models.UniqueConstraint(
                fields=("forecast", "district"),
                name="unique_district_per_forecast",
            ),
        ),
    ]
