# Generated by Django 5.2.7 on 2026-05-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0016_force_unique_district_per_forecast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtforecastdetails',
            name='temp_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='districtforecastdetails',
            name='temp_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='districtforecastdetails',
            name='winds_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='districtforecastdetails',
            name='winds_min',
            field=models.IntegerField(default=0),
        ),
    ]
