# Generated by Django 5.2.7 on 2026-06-30 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0019_rename_description_districtforecastinstructionscategory_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtforecastinstructions',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructions_category', to='forecasts.districtforecastinstructionscategory'),
        ),
    ]
