# Generated by Django 5.2.7 on 2026-07-02 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0020_districtforecastinstructions_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtforecastinstructions',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions_category', to='forecasts.districtforecastinstructionscategory'),
        ),
    ]
