# Generated by Django 5.2.7 on 2026-07-28 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0022_forecastgeneral'),
        ('system_core', '0010_remove_officelocation_building_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtforecastdetails',
            name='sev_temp_min',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='severity_temp_min', to='system_core.alertlevel'),
        ),
        migrations.AlterField(
            model_name='districtforecastdetails',
            name='sev_temp_max',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='severity_temp_max', to='system_core.alertlevel'),
        ),
        migrations.AlterField(
            model_name='districtforecastdetails',
            name='sev_weather_conditions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='severity_weather_conditions', to='system_core.alertlevel'),
        ),
        migrations.AlterField(
            model_name='districtforecastdetails',
            name='prob_winds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='probability_winds', to='system_core.alertlevel'),
        ),
        migrations.AlterField(
            model_name='districtforecastdetails',
            name='sev_winds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='severity_winds', to='system_core.alertlevel'),
        ),
        migrations.AlterField(
            model_name='districtforecastdetails',
            name='prob_temp_min',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='probability_temp_min', to='system_core.alertlevel'),
        ),
        migrations.AlterField(
            model_name='districtforecastdetails',
            name='prob_weather_conditions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='probability_weather_conditions', to='system_core.alertlevel'),
        ),
        migrations.AlterField(
            model_name='districtforecastdetails',
            name='prob_precip_max',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='probability_precip_max', to='system_core.alertlevel'),
        ),
        migrations.AlterField(
            model_name='districtforecastdetails',
            name='sev_precip_max',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='severity_precip_max', to='system_core.alertlevel'),
        ),
        migrations.AlterField(
            model_name='districtforecastdetails',
            name='prob_temp_max',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='probability_temp_max', to='system_core.alertlevel'),
        ),
        migrations.AlterField(
            model_name='districtforecastdetails',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_details', to='system_core.district'),
        ),
        migrations.AlterField(
            model_name='districtforecastdetails',
            name='risk_temp_min',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_temp_min', to='system_core.risklevel'),
        ),
        migrations.AlterField(
            model_name='districtforecastdetails',
            name='risk_temp_max',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_temp_max', to='system_core.risklevel'),
        ),
        migrations.AlterField(
            model_name='districtforecastdetails',
            name='risk_winds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_winds', to='system_core.risklevel'),
        ),
        migrations.AlterField(
            model_name='districtforecastdetails',
            name='risk_precip_max',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_precip_max', to='system_core.risklevel'),
        ),
        migrations.AlterField(
            model_name='districtforecastdetails',
            name='risk_weather_conditions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_weather_conditions', to='system_core.risklevel'),
        ),
        migrations.DeleteModel(
            name='AlertLevel',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='RiskLevel',
        ),
    ]
