# Generated by Django 5.2.7 on 2026-07-30 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0024_alter_forecastgeneral_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastgeneral',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='forecastgeneral',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='forecastgeneral',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='forecastgeneral',
            name='updated_time',
        ),
    ]
