# Generated by Django 5.2.7 on 2026-03-17 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='InventoryCategory',
        ),
        migrations.RenameModel(
            old_name='Placement',
            new_name='OfficeLocationPlacement',
        ),
    ]
