# Generated by Django 5.2.7 on 2026-05-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_category_inventorycategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='purchase_date',
            new_name='acquisition_date',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='purchase_cost',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='sponsor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
