# Generated by Django 5.2.7 on 2026-05-26 16:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_purchase_date_inventoryitem_acquisition_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={},
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='name',
            new_name='device_label',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='acquisition_date',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='asset_tag',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='model',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='sponsor',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='status',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='assigned_user',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='department_section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='device_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='floor_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
