# Generated by Django 5.2.7 on 2026-05-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventoryitem_acquisition_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Department Sections',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='device_status',
            field=models.IntegerField(choices=[('1', 'Available'), ('2', 'In Use'), ('3', 'Under Maintenance'), ('4', 'Damaged'), ('5', 'Retired')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='floor_level',
            field=models.CharField(blank=True, choices=[('1', 'Ground Floor'), ('2', 'Second Floor'), ('3', 'Third Floor')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='service_tag',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
