# Generated by Django 5.2.7 on 2026-05-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_departmentsection_alter_inventoryitem_device_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentsection',
            name='description',
        ),
        migrations.AddField(
            model_name='departmentsection',
            name='short_name',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
