# Generated by Django 5.2.7 on 2026-05-26 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_departmentsection_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='department_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.departmentsection'),
        ),
    ]
