# Generated by Django 5.2.7 on 2026-05-26 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_inventoryitem_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='is_active',
        ),
    ]
