# Generated by Django 5.2.7 on 2026-05-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_inventoryitem_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='device_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
