# Generated by Django 5.2.7 on 2026-05-27 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_devicetype_alter_inventoryitem_device_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetype',
            name='description',
        ),
        migrations.AddField(
            model_name='devicetype',
            name='inventory_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_types', to='inventory.inventorycategory'),
        ),
    ]
