# Generated by Django 5.2.7 on 2026-05-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_devicetype_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='device_status',
            field=models.IntegerField(choices=[(1, 'Available'), (2, 'In Use'), (3, 'Under Maintenance'), (4, 'Damaged'), (5, 'Retired')], default='1', max_length=20),
        ),
    ]
