# Generated by Django 5.2.7 on 2026-05-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_inventoryitem_device_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='assigned_user',
            field=models.CharField(max_length=100),
        ),
    ]
