# Generated by Django 5.2.7 on 2026-05-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_inventoryitem_assigned_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='device_label',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='device_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
