# Generated by Django 5.2.7 on 2026-05-27 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_sponsor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['device_label'], 'verbose_name': 'Inventory Item', 'verbose_name_plural': 'Inventory Items'},
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='disk',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='mac_address',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='operating_system',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='service_tag',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_item_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_item_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HardwareSpecifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_item', models.CharField(max_length=200, unique=True)),
                ('service_tag', models.CharField(blank=True, max_length=30, null=True)),
                ('express_service_code', models.CharField(blank=True, max_length=30, null=True)),
                ('processor', models.CharField(blank=True, max_length=100, null=True)),
                ('ram', models.CharField(blank=True, max_length=100, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=100, null=True)),
                ('disk_size', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardware_specs_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardware_specs_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_item', models.CharField(max_length=200, unique=True)),
                ('mac_address', models.CharField(blank=True, max_length=150, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=150, null=True)),
                ('switch_port_number', models.CharField(blank=True, max_length=150, null=True)),
                ('cabinet', models.CharField(blank=True, choices=[('A', 'Cabinet A'), ('B', 'Cabinet B')], max_length=150, null=True)),
                ('rack_number', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_details_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_details_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Network Details',
                'verbose_name_plural': 'Network Details',
                'ordering': ['inventory_item'],
            },
        ),
    ]
