# Generated by Django 5.2.7 on 2026-05-27 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_inventoryitem_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sponsor',
            new_name='Vendor',
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['name'], 'verbose_name_plural': 'Vendors'},
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='sponsor',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.vendor'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='device_status',
            field=models.IntegerField(choices=[(1, 'Available'), (2, 'In Use'), (3, 'Under Maintenance'), (4, 'Damaged'), (5, 'Retired')], default=1, max_length=20),
        ),
    ]
