# Generated by Django 5.2.7 on 2026-05-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_rename_sponsor_vendor_alter_vendor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='short_name',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
