# Generated by Django 5.2.7 on 2026-07-23 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0021_vendor_short_name"),
        ("system_core", "0007_departmentsection_officelocationplacement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="department_section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="system_core.departmentsection",
            ),
        ),

        # Move the relationship before deleting the old inventory model.
        migrations.AlterField(
            model_name="inventoryitem",
            name="placement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="system_core.officelocationplacement",
            ),
        ),

        migrations.DeleteModel(
            name="OfficeLocationPlacement",
        ),

        migrations.DeleteModel(
            name="DepartmentSection",
        ),
    ]