# Generated by Django 5.2.7 on 2026-07-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_inventoryitem_department_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='device_status',
            field=models.IntegerField(choices=[(1, 'Available'), (2, 'In Use'), (3, 'Under Maintenance'), (4, 'Damaged'), (5, 'Retired')], default=1),
        ),
    ]
