# Generated by Django 5.2.7 on 2026-07-24 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_alter_inventoryitem_device_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='floor_level',
        ),
    ]
