# Generated by Django 5.2.7 on 2026-07-27 17:38

import django.db.models.deletion
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_alter_inventoryitem_assigned_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=inventory.models.inventory_photo_upload_path)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Use this photo as the main inventory image.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inventory.inventoryitem')),
            ],
            options={
                'verbose_name': 'Inventory Item Photo',
                'verbose_name_plural': 'Inventory Item Photos',
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
    ]
