# Generated by Django 5.2.7 on 2026-08-11 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_inventoryitemphoto'),
        ('users', '0015_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwarespecifications',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_item_hardware', to='inventory.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inventory', to='users.employee'),
        ),
        migrations.AlterField(
            model_name='networkdetails',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_item_network', to='inventory.inventoryitem'),
        ),
    ]
