# Generated by Django 5.2.7 on 2026-08-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_alter_hardwarespecifications_inventory_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdetails',
            name='mac_address_wireless',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
