# Generated by Django 5.2.7 on 2026-05-08 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100, unique=True)),
                ('published_date', models.DateTimeField(auto_now=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['district_name'],
            },
        ),
        migrations.CreateModel(
            name='DistrictForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Probability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
                ('color', models.CharField(blank=True, default='#ffffff', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
                ('color', models.CharField(blank=True, default='#ffffff', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictForecastDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField(blank=True, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_details', to='forecasts.district')),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='forecasts.districtforecast')),
                ('probability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forecasts.probability')),
                ('risk_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forecasts.risklevel')),
                ('severity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forecasts.severity')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('forecast', 'district'), name='unique_district_per_forecast')],
            },
        ),
    ]
