# Generated by Django 5.2.7 on 2026-05-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0004_rename_max_precip_districtforecastdetails_precip_max'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
                ('color', models.CharField(blank=True, default='', max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='probability',
            name='color',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='risklevel',
            name='color',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='severity',
            name='color',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
