# Generated by Django 5.2.7 on 2026-05-13 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0006_districtforecastdetails_prob_temp_max'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictForecastInstructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='districtforecastdetails',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='districtforecastdetails',
            name='probability',
        ),
        migrations.RemoveField(
            model_name='districtforecastdetails',
            name='risk_level',
        ),
        migrations.RemoveField(
            model_name='districtforecastdetails',
            name='severity',
        ),
        migrations.AddField(
            model_name='districtforecastdetails',
            name='prob_precip_max',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='probability_precip_max', to='forecasts.alertlevel'),
        ),
        migrations.AddField(
            model_name='districtforecastdetails',
            name='prob_temp_min',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='probability_temp_min', to='forecasts.alertlevel'),
        ),
        migrations.AddField(
            model_name='districtforecastdetails',
            name='prob_weather_conditions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='probability_weather_conditions', to='forecasts.alertlevel'),
        ),
        migrations.AddField(
            model_name='districtforecastdetails',
            name='prob_winds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='probability_winds', to='forecasts.alertlevel'),
        ),
        migrations.AddField(
            model_name='districtforecastdetails',
            name='sev_precip_max',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='severity_precip_max', to='forecasts.alertlevel'),
        ),
        migrations.AddField(
            model_name='districtforecastdetails',
            name='sev_temp_max',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='severity_temp_max', to='forecasts.alertlevel'),
        ),
        migrations.AddField(
            model_name='districtforecastdetails',
            name='sev_temp_min',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='severity_temp_min', to='forecasts.alertlevel'),
        ),
        migrations.AddField(
            model_name='districtforecastdetails',
            name='sev_weather_conditions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='severity_weather_conditions', to='forecasts.alertlevel'),
        ),
        migrations.AddField(
            model_name='districtforecastdetails',
            name='sev_winds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='severity_winds', to='forecasts.alertlevel'),
        ),
        migrations.AlterField(
            model_name='districtforecastdetails',
            name='prob_temp_max',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='probability_temp_max', to='forecasts.alertlevel'),
        ),
        migrations.AddField(
            model_name='districtforecastdetails',
            name='ins_precip_max',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructions_precip_max', to='forecasts.districtforecastinstructions'),
        ),
        migrations.AddField(
            model_name='districtforecastdetails',
            name='ins_temp_max',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructions_temp_max', to='forecasts.districtforecastinstructions'),
        ),
        migrations.AddField(
            model_name='districtforecastdetails',
            name='ins_temp_min',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructions_temp_min', to='forecasts.districtforecastinstructions'),
        ),
        migrations.AddField(
            model_name='districtforecastdetails',
            name='ins_weather_conditions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructions_weather_conditions', to='forecasts.districtforecastinstructions'),
        ),
        migrations.AddField(
            model_name='districtforecastdetails',
            name='ins_winds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructions_winds', to='forecasts.districtforecastinstructions'),
        ),
    ]
