# Generated by Django 5.2.7 on 2026-05-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0008_alter_districtforecastinstructions_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='districtforecastdetails',
            old_name='winds',
            new_name='winds_max',
        ),
        migrations.AddField(
            model_name='districtforecastdetails',
            name='winds_min',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
