# Generated by Django 5.2.7 on 2026-05-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0012_alter_districtforecastdetails_risk_precip_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtforecastdetails',
            name='winds_max',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='districtforecastdetails',
            name='winds_min',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
    ]
