# Generated by Django 5.2.7 on 2026-05-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0014_alter_districtforecastdetails_temp_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtforecastdetails',
            name='precip_max',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
