# Generated by Django 5.2.7 on 2026-06-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0017_alter_districtforecastdetails_temp_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictForecastInstructionsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
