# Generated by Django 5.2.7 on 2026-06-30 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0018_districtforecastinstructionscategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='districtforecastinstructionscategory',
            old_name='description',
            new_name='category_name',
        ),
    ]
