# Generated by Django 5.2.7 on 2026-07-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0021_alter_districtforecastinstructions_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('forecast_time', models.TimeField(blank=True, null=True)),
                ('forecast_type', models.IntegerField(blank=True, null=True)),
                ('general_situation', models.CharField(max_length=255)),
                ('twenty_four_hour_forecast', models.CharField(max_length=1000)),
                ('light_variable', models.IntegerField(blank=True, null=True)),
                ('wind_speed', models.CharField(max_length=10)),
                ('wind_direction', models.CharField(blank=True, max_length=50, null=True)),
                ('wind_condition', models.CharField(blank=True, max_length=50, null=True)),
                ('wind_shift_speed', models.CharField(blank=True, max_length=10, null=True)),
                ('wind_shift_direction', models.CharField(blank=True, max_length=50, null=True)),
                ('wind_shift_condition', models.CharField(blank=True, max_length=50, null=True)),
                ('sea_state', models.CharField(max_length=255)),
                ('wave', models.CharField(blank=True, max_length=10, null=True)),
                ('sea_state_shift', models.CharField(blank=True, max_length=255, null=True)),
                ('wave_shift', models.CharField(blank=True, max_length=10, null=True)),
                ('advisory', models.CharField(max_length=1000)),
                ('outlook', models.CharField(max_length=1000)),
                ('coast_high_f', models.IntegerField()),
                ('coast_high_c', models.IntegerField(blank=True, null=True)),
                ('coast_low_f', models.IntegerField()),
                ('coast_low_c', models.IntegerField(blank=True, null=True)),
                ('inland_high_f', models.IntegerField()),
                ('inland_high_c', models.IntegerField(blank=True, null=True)),
                ('inland_low_f', models.IntegerField()),
                ('inland_low_c', models.IntegerField(blank=True, null=True)),
                ('hills_high_f', models.IntegerField()),
                ('hills_high_c', models.IntegerField(blank=True, null=True)),
                ('hills_low_f', models.IntegerField()),
                ('hills_low_c', models.IntegerField(blank=True, null=True)),
                ('publish_to_web', models.BooleanField()),
                ('forecaster_id', models.IntegerField()),
                ('created_by', models.CharField(max_length=11)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(max_length=11)),
                ('updated_time', models.DateTimeField(blank=True, null=True)),
                ('auto_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_forecast_general',
            },
        ),
    ]
