# Generated by Django 5.2.7 on 2026-07-28 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0023_alter_districtforecastdetails_sev_winds_and_more'),
    ]


    operations = [
        migrations.AlterField(
            model_name='forecastgeneral',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_forecasts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forecastgeneral',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_forecasts_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
