# Generated by Django 5.2.7 on 2026-08-05 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0026_forescastgeneralcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='districtforecast',
            options={'verbose_name': 'District Level Forecast', 'verbose_name_plural': 'District Level Forecasts'},
        ),
        migrations.AlterModelOptions(
            name='districtforecastdetails',
            options={'verbose_name': 'District Level Forecast Details', 'verbose_name_plural': 'District Level Forecast Details'},
        ),
        migrations.AlterModelOptions(
            name='districtforecastinstructions',
            options={'verbose_name': 'District Level Forecast Instruction', 'verbose_name_plural': 'District Level Forecast Instructions'},
        ),
        migrations.AlterModelOptions(
            name='districtforecastinstructionscategory',
            options={'verbose_name': 'District Level Forecast Instructions Category', 'verbose_name_plural': 'District Level Forecast Instructions Categories'},
        ),
        migrations.AlterModelOptions(
            name='forecastgeneral',
            options={'verbose_name': 'General Weather Forecast', 'verbose_name_plural': 'General Weather Forecasts'},
        ),
        migrations.AlterModelOptions(
            name='forescastgeneralcategory',
            options={'verbose_name': 'General Weather Forecast Category', 'verbose_name_plural': 'General Weather Forecast Categories'},
        ),
        migrations.AlterModelTable(
            name='forecastgeneral',
            table=None,
        ),
    ]
