# Generated by Django 5.2.7 on 2026-08-05 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0027_alter_districtforecast_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecastgeneral',
            old_name='thr_forecast',
            new_name='twenty_four_hour_forecast',
        ),
    ]
