# Generated by Django 5.2.7 on 2026-08-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0028_rename_thr_forecast_forecastgeneral_twenty_four_hour_forecast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastgeneral',
            name='auto_update',
        ),
        migrations.AddField(
            model_name='forecastgeneral',
            name='legacy_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
