# Generated by Django 5.2.7 on 2026-08-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0029_remove_forecastgeneral_auto_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastgeneral',
            name='created_by',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='forecastgeneral',
            name='created_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forecastgeneral',
            name='updated_by',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='forecastgeneral',
            name='updated_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
