# Generated by Django 5.2.7 on 2026-08-05 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0030_forecastgeneral_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecastgeneral',
            old_name='created_time',
            new_name='created_datetime',
        ),
        migrations.RenameField(
            model_name='forecastgeneral',
            old_name='updated_time',
            new_name='updated_datetime',
        ),
    ]
