# Generated by Django 5.2.7 on 2026-08-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0031_rename_created_time_forecastgeneral_created_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastgeneral',
            name='advisory',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='forecastgeneral',
            name='coast_high_f',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastgeneral',
            name='coast_low_f',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastgeneral',
            name='forecaster_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastgeneral',
            name='general_situation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='forecastgeneral',
            name='hills_high_f',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastgeneral',
            name='hills_low_f',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastgeneral',
            name='inland_high_f',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastgeneral',
            name='outlook',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='forecastgeneral',
            name='sea_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='forecastgeneral',
            name='twenty_four_hour_forecast',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='forecastgeneral',
            name='wind_speed',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
