# Generated by Django 5.2.7 on 2026-08-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0032_alter_forecastgeneral_advisory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastgeneral',
            name='publish_to_web',
        ),
        migrations.AddField(
            model_name='forecastgeneral',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='forecastgeneral',
            name='inland_low_f',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
