# Generated by Django 5.2.7 on 2026-08-05 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0033_remove_forecastgeneral_publish_to_web_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecastgeneral',
            old_name='forecast_type',
            new_name='forecast_category',
        ),
    ]
