# Generated by Django 5.2.7 on 2026-08-05 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0034_rename_forecast_type_forecastgeneral_forecast_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastgeneral',
            name='forecast_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_general_category', to='forecasts.forescastgeneralcategory'),
        ),
    ]
