# Generated by Django 5.2.7 on 2026-08-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0035_alter_forecastgeneral_forecast_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastgeneral',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='general_forecast/{self.forecast_date}/'),
        ),
    ]
