# Generated by Django 5.2.7 on 2026-08-11 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0036_forecastgeneral_audio_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastgeneral',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_forecasts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forecastgeneral',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_forecasts_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
