# Generated by Django 5.2.7 on 2026-08-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0039_windcondition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastgeneral',
            name='wind_direction',
        ),
        migrations.AddField(
            model_name='forecastgeneral',
            name='wind_direction',
            field=models.ManyToManyField(blank=True, related_name='forecasts', to='forecasts.winddirection'),
        ),
    ]
