# Generated by Django 5.2.7 on 2026-08-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0044_fix_sea_state_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastgeneral',
            name='sea_state_shift_m2m',
            field=models.ManyToManyField(blank=True, related_name='general_forecasts_shift', to='forecasts.seastate'),
        ),
    ]
