# Generated by Django 5.2.7 on 2026-08-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0046_migrate_sea_state_shift_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastgeneral',
            name='wind_direction_m2m',
            field=models.ManyToManyField(blank=True, related_name='general_forecasts_wind_direction', to='forecasts.winddirection'),
        ),
        migrations.RemoveField(
            model_name='forecastgeneral',
            name='wind_direction',
        ),
        migrations.AddField(
            model_name='forecastgeneral',
            name='wind_direction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
