# Generated by Django 5.2.7 on 2026-08-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0047_forecastgeneral_wind_direction_m2m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastgeneral',
            name='wind_condition_m2m',
            field=models.ManyToManyField(blank=True, related_name='general_forecasts_wind_condition', to='forecasts.windcondition'),
        ),
    ]
