# Generated by Django 5.2.7 on 2026-08-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0049_migrate_wind_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastgeneral',
            name='wind_shift_condition_m2m',
            field=models.ManyToManyField(blank=True, related_name='general_forecasts_wind_condition_shift', to='forecasts.windcondition'),
        ),
        migrations.AddField(
            model_name='forecastgeneral',
            name='wind_shift_direction_m2m',
            field=models.ManyToManyField(blank=True, related_name='general_forecasts_wind_direction_shift', to='forecasts.winddirection'),
        ),
    ]
