# Generated by Django 5.2.7 on 2026-08-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0016_remove_capalertdetails_event_code'),
        ('forecasts', '0051_migrate_wind_shift_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastgeneral',
            name='cap_alerts',
            field=models.ManyToManyField(blank=True, related_name='general_forecasts_cap', to='alerts.capalertdetails'),
        ),
    ]
