# Generated by Django 5.2.7 on 2026-08-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0016_remove_capalertdetails_event_code'),
        ('forecasts', '0052_forecastgeneral_cap_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastgeneral',
            name='tropical_alerts',
            field=models.ManyToManyField(blank=True, related_name='general_forecasts_cap', to='alerts.tropicalweatheralerts'),
        ),
    ]
