# Generated by Django 5.2.7 on 2026-08-27 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0053_forecastgeneral_tropical_alerts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastMarine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('forecast_date', models.DateField()),
                ('forecast_time', models.TimeField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='marine_forecast/{self.forecast_date}/')),
                ('synopsis', models.CharField(blank=True, max_length=255, null=True)),
                ('sea_surface_temperature', models.IntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('forecaster_id', models.IntegerField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(blank=True, null=True)),
                ('updated_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marine_forecasts_created', to=settings.AUTH_USER_MODEL)),
                ('forecast_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_marine_category', to='forecasts.forescastgeneralcategory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marine_forecasts_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marine Forecast',
                'verbose_name_plural': 'Marine Forecasts',
            },
        ),
        migrations.CreateModel(
            name='ForescastMarineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marine_forecasts_category_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marine_forecasts_category_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marine Forecast Category',
                'verbose_name_plural': 'Marine Forecast Categories',
            },
        ),
    ]
