# Generated by Django 5.2.7 on 2026-08-27 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0054_forecastmarine_forescastmarinecategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastmarine',
            name='audio_file',
        ),
        migrations.AddField(
            model_name='forecastmarine',
            name='advisory',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='forecastmarine',
            name='forecast_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_marine_category', to='forecasts.forescastmarinecategory'),
        ),
    ]
