# Generated by Django 5.2.7 on 2026-08-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0055_remove_forecastmarine_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastmarine',
            name='max_temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forecastmarine',
            name='min_temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
