# Generated by Django 5.2.7 on 2026-08-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0016_remove_capalertdetails_event_code'),
        ('forecasts', '0056_forecastmarine_max_temperature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastmarine',
            name='cap_alerts',
            field=models.ManyToManyField(blank=True, related_name='marine_forecasts_cap', to='alerts.capalertdetails'),
        ),
        migrations.AddField(
            model_name='forecastmarine',
            name='tropical_alerts',
            field=models.ManyToManyField(blank=True, related_name='marine_forecasts_cap', to='alerts.tropicalweatheralerts'),
        ),
    ]
