# Generated by Django 5.2.7 on 2026-08-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0058_forescastmarinedetailscategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districtforecastdetails',
            name='ins_precip_max',
        ),
        migrations.AddField(
            model_name='districtforecastdetails',
            name='ins_precip_max',
            field=models.ManyToManyField(blank=True, to='forecasts.districtforecastinstructions'),
        ),
    ]
