# Generated by Django 5.2.7 on 2026-08-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0059_remove_districtforecastdetails_ins_precip_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtforecastdetails',
            name='ins_precip_max',
            field=models.ManyToManyField(blank=True, related_name='instructions_precip_max', to='forecasts.districtforecastinstructions'),
        ),
        migrations.RemoveField(
            model_name='districtforecastdetails',
            name='ins_temp_max',
        ),
        migrations.RemoveField(
            model_name='districtforecastdetails',
            name='ins_temp_min',
        ),
        migrations.RemoveField(
            model_name='districtforecastdetails',
            name='ins_weather_conditions',
        ),
        migrations.RemoveField(
            model_name='districtforecastdetails',
            name='ins_winds',
        ),
        migrations.AddField(
            model_name='districtforecastdetails',
            name='ins_temp_max',
            field=models.ManyToManyField(blank=True, related_name='instructions_temp_max', to='forecasts.districtforecastinstructions'),
        ),
        migrations.AddField(
            model_name='districtforecastdetails',
            name='ins_temp_min',
            field=models.ManyToManyField(blank=True, related_name='instructions_temp_min', to='forecasts.districtforecastinstructions'),
        ),
        migrations.AddField(
            model_name='districtforecastdetails',
            name='ins_weather_conditions',
            field=models.ManyToManyField(blank=True, related_name='instructions_weather_conditions', to='forecasts.districtforecastinstructions'),
        ),
        migrations.AddField(
            model_name='districtforecastdetails',
            name='ins_winds',
            field=models.ManyToManyField(blank=True, related_name='instructions_winds', to='forecasts.districtforecastinstructions'),
        ),
    ]
