# Generated by Django 5.2.7 on 2026-09-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0060_alter_districtforecastdetails_ins_precip_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtforecastdetails',
            name='precip_max',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
