# Generated by Django 5.2.7 on 2026-09-07 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0061_remove_forecastgeneral_thr_forecast_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='forecastgeneral',
        #    name='thr_forecast',
        #),
        migrations.AddField(
            model_name='districtforecastdetails',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_forecast_details_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='districtforecastdetails',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='districtforecastdetails',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_forecast_details_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='districtforecastdetails',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
