# Generated by Django 5.2.7 on 2026-09-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0062_remove_forecastgeneral_thr_forecast_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='forecastgeneral',
                    name='thr_forecast',
                ),
            ],
        ),
       migrations.AddField(
            model_name='districtforecastdetails',
            name='precip_min',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
