# Generated by Django 5.2.7 on 2026-09-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0063_remove_forecastgeneral_thr_forecast_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='districtforecastdetails',
            old_name='temp_max',
            new_name='temp_max_high',
        ),
        migrations.RenameField(
            model_name='districtforecastdetails',
            old_name='temp_min',
            new_name='temp_min_high',
        ),
    ]
