# Generated by Django 5.2.7 on 2026-09-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0064_rename_temp_max_districtforecastdetails_temp_max_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtforecastdetails',
            name='temp_max_low',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='districtforecastdetails',
            name='temp_min_low',
            field=models.IntegerField(default=0),
        ),
    ]
