# Generated by Django 5.2.7 on 2026-09-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0065_districtforecastdetails_temp_max_low_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastgeneral',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='general/{self.forecast_date}/'),
        ),
    ]
