# Generated by Django 5.2.7 on 2026-09-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0067_alter_forecastgeneral_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastgeneral',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='forecast/general/audio/'),
        ),
    ]
