# Generated by Django 5.2.7 on 2026-09-23 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0070_alter_forecastgeneral_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastgeneral',
            name='forecast_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
