# Generated by Django 5.2.7 on 2026-09-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0071_alter_forecastgeneral_forecast_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastgeneral',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='forecastgeneral',
            name='updated_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
