# Generated by Django 5.2.7 on 2026-09-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0072_alter_forecastgeneral_created_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastgeneral',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
