# Generated by Django 5.2.7 on 2026-09-23 20:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0073_alter_forecastgeneral_updated_datetime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('forecast_time', models.TimeField(default=datetime.time(0, 0))),
                ('forecast_type', models.IntegerField(blank=True, null=True)),
                ('forecast_discussion', models.CharField(blank=True, max_length=5000, null=True)),
                ('forecast_id', models.IntegerField(blank=True, null=True)),
                ('forecast', models.CharField(blank=True, max_length=255, null=True)),
                ('outlook', models.CharField(blank=True, max_length=1000, null=True)),
                ('advisory', models.CharField(blank=True, max_length=1000, null=True)),
                ('wind_speed', models.CharField(blank=True, max_length=255, null=True)),
                ('wind_direction', models.CharField(blank=True, max_length=255, null=True)),
                ('wind_condition', models.CharField(blank=True, max_length=255, null=True)),
                ('sea_state', models.CharField(blank=True, max_length=255, null=True)),
                ('marine_wave', models.CharField(blank=True, max_length=255, null=True)),
                ('wave', models.CharField(blank=True, max_length=11, null=True)),
                ('forecaster_id', models.IntegerField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('auto_update', models.DateTimeField(blank=True, null=True)),
                ('legacy_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_discussions_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_discussions_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forecast Discussion',
                'verbose_name_plural': 'Forecast Discussions',
                'ordering': ['-forecast_date', '-forecast_time'],
            },
        ),
    ]
