# Generated by Django 5.2.7 on 2026-09-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0074_forecastdiscussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastdiscussion',
            name='forecast_discussion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
