# Generated by Django 5.2.7 on 2026-09-23 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0075_alter_forecastdiscussion_forecast_discussion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastdiscussion',
            name='forecast_type',
        ),
        migrations.AddField(
            model_name='forecastdiscussion',
            name='forecast_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_discussion_category', to='forecasts.forescastgeneralcategory'),
        ),
    ]
