# Generated by Django 5.2.7 on 2026-09-23 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0076_remove_forecastdiscussion_forecast_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastdiscussion',
            name='forecast_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_discussions', to='forecasts.forecastgeneral'),
        ),
    ]
