# Generated by Django 5.2.7 on 2026-09-23 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0077_alter_forecastdiscussion_forecast_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecastdiscussion',
            old_name='forecast',
            new_name='forecast_text',
        ),
    ]
