# Generated by Django 5.2.7 on 2026-09-24 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0078_rename_forecast_forecastdiscussion_forecast_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecastdiscussion',
            old_name='forecast_id',
            new_name='general_forecast',
        ),
    ]
