# Generated by Django 5.2.7 on 2026-09-24 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0079_rename_forecast_id_forecastdiscussion_general_forecast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastdiscussion',
            name='forecast_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastdiscussion',
            name='forecast_time',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
    ]
