# Generated by Django 5.2.7 on 2026-09-24 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0080_alter_forecastdiscussion_forecast_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastmarine',
            name='forecast_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
