# Generated by Django 5.2.7 on 2026-09-24 17:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0081_alter_forecastmarine_forecast_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForescastMarineCategory',
            new_name='ForecastMarineCategory',
        ),
        migrations.RenameModel(
            old_name='ForescastMarineDetailsCategory',
            new_name='ForecastMarineDetailsCategory',
        ),
        migrations.RemoveField(
            model_name='forecastmarine',
            name='forecast_category',
        ),
    ]
