# Generated by Django 5.2.7 on 2026-09-24 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0082_rename_forescastmarinecategory_forecastmarinecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastmarine',
            name='forecast_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_marine_category', to='forecasts.forecastmarinecategory'),
        ),
    ]
