# Generated by Django 5.2.7 on 2026-09-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0083_forecastmarine_forecast_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastmarine',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastmarine',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
