# Generated by Django 5.2.7 on 2026-09-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0084_alter_forecastmarine_created_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastdiscussion',
            name='created_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastdiscussion',
            name='updated_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
