# Generated by Django 5.2.7 on 2026-09-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0085_alter_forecastdiscussion_created_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastdiscussion',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastdiscussion',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
