# Generated by Django 5.2.7 on 2026-09-24 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0086_alter_forecastdiscussion_created_datetime_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastMarineDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('wind_speed', models.CharField(blank=True, max_length=10, null=True)),
                ('wind_direction', models.CharField(blank=True, max_length=50, null=True)),
                ('wind_shift_condition', models.CharField(blank=True, max_length=50, null=True)),
                ('sea_state', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marine_forecasts_details_created', to=settings.AUTH_USER_MODEL)),
                ('sea_state_m2m', models.ManyToManyField(blank=True, related_name='marine_forecast_details_sea_state', to='forecasts.seastate')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marine_forecasts_details_updated', to=settings.AUTH_USER_MODEL)),
                ('wind_direction_m2m', models.ManyToManyField(blank=True, related_name='marine_forecast_details_forecasts_wind_direction', to='forecasts.winddirection')),
                ('wind_shift_condition_m2m', models.ManyToManyField(blank=True, related_name='marine_forecast_details_wind_condition_shift', to='forecasts.windcondition')),
            ],
            options={
                'verbose_name': 'Marine Forecast Details',
                'verbose_name_plural': 'Marine Forecast Details',
            },
        ),
    ]
