# Generated by Django 5.2.7 on 2026-09-25 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0087_forecastmarinedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastmarinedetails',
            name='marine_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_general_category', to='forecasts.forecastmarinedetailscategory'),
        ),
    ]
