# Generated by Django 5.2.7 on 2026-09-25 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0088_forecastmarinedetails_marine_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastmarinedetails',
            name='marine_forecast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_marine_details', to='forecasts.forecastmarine'),
        ),
        migrations.AlterField(
            model_name='forecastmarinedetails',
            name='marine_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_marine_details', to='forecasts.forecastmarinedetailscategory'),
        ),
    ]
