# Generated by Django 5.2.7 on 2026-09-25 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0089_forecastmarinedetails_marine_forecast_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastmarinedetails',
            name='wind_shift_condition_m2m',
        ),
    ]
