# Generated by Django 5.2.7 on 2026-09-25 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0090_remove_forecastmarinedetails_wind_shift_condition_m2m'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecastmarinedetails',
            old_name='wind_shift_condition',
            new_name='wind_condition',
        ),
    ]
