# Generated by Django 5.2.7 on 2026-09-25 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0091_rename_wind_shift_condition_forecastmarinedetails_wind_condition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TideDayCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tide_day_category_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tide_day_category_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tides Day Category',
                'verbose_name_plural': 'Tides Day Categories',
            },
        ),
        migrations.CreateModel(
            name='TideLevelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tide_level_category_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tide_level_category_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tide Level Category',
                'verbose_name_plural': 'Tide Level Categories',
            },
        ),
        migrations.CreateModel(
            name='Tides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tide_date', models.DateField()),
                ('tide_time', models.TimeField()),
                ('general_forecast', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('marine_forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marine_tides', to='forecasts.forecastmarine')),
                ('tide_date_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marine_tides_day_category', to='forecasts.tidedaycategory')),
                ('tide_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marine_tides_level', to='forecasts.tidelevelcategory')),
            ],
            options={
                'db_table': 'tbl_forecast_marine_tide',
                'ordering': ['tide_date', 'tide_time'],
            },
        ),
    ]
