# Generated by Django 5.2.7 on 2026-09-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0092_tidedaycategory_tidelevelcategory_tides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tides',
            name='tide_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tides',
            name='tide_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='tides',
            table=None,
        ),
    ]
