# Generated by Django 5.2.7 on 2026-09-25 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0093_alter_tides_tide_date_alter_tides_tide_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tides',
            old_name='tide_date_type',
            new_name='tide_day_category',
        ),
        migrations.RenameField(
            model_name='tides',
            old_name='tide_type',
            new_name='tide_level_category',
        ),
    ]
