# Generated by Django 5.2.7 on 2026-09-25 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0094_rename_tide_date_type_tides_tide_day_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tides',
            name='marine_forecast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marine_tides', to='forecasts.forecastmarine'),
        ),
        migrations.AlterField(
            model_name='tides',
            name='tide_day_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marine_tides_day_category', to='forecasts.tidedaycategory'),
        ),
        migrations.AlterField(
            model_name='tides',
            name='tide_level_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marine_tides_level', to='forecasts.tidelevelcategory'),
        ),
    ]
