# Generated by Django 5.2.7 on 2026-09-25 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0095_alter_tides_marine_forecast_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoonDayCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moon_day_category_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moon_day_category_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moon - Day Category',
                'verbose_name_plural': 'Moon - Day Categories',
            },
        ),
        migrations.CreateModel(
            name='MoonMovementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moon_type_category_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moon_type_category_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moon Movement Category',
                'verbose_name_plural': 'Moon Movement Categories',
            },
        ),
        migrations.CreateModel(
            name='MoonRiseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moon_date', models.DateField(blank=True, null=True)),
                ('moon_time', models.TimeField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moonrise_set_created', to=settings.AUTH_USER_MODEL)),
                ('marine_forecast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moonrise_set', to='forecasts.forecastmarine')),
                ('moon_day_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moonrise_set_day_category', to='forecasts.moondaycategory')),
                ('moon_move_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moonrise_set_category', to='forecasts.moonmovementcategory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moonrise_set_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moonrise / Moonset',
                'verbose_name_plural': 'Moonrise / Moonset',
            },
        ),
        migrations.CreateModel(
            name='SunDayCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sun_day_category_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sun_day_category_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sun - Day Category',
                'verbose_name_plural': 'Sun - Day Categories',
            },
        ),
        migrations.CreateModel(
            name='SunMovementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sun_type_category_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sun_type_category_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sun Movement Category',
                'verbose_name_plural': 'Sun Movement Categories',
            },
        ),
        migrations.CreateModel(
            name='SunRiseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sun_date', models.DateField(blank=True, null=True)),
                ('sun_time', models.TimeField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunrise_set_created', to=settings.AUTH_USER_MODEL)),
                ('marine_forecast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sunrise_set', to='forecasts.forecastmarine')),
                ('sun_day_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunrise_set_day_category', to='forecasts.sundaycategory')),
                ('sun_move_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunrise_set_category', to='forecasts.sunmovementcategory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunrise_set_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sunrise / Sunset',
                'verbose_name_plural': 'Sunrise / Sunset',
            },
        ),
    ]
