# Generated by Django 5.2.7 on 2026-07-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core', '0004_months_district_zone_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='months',
            name='short_name',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
