# Generated by Django 5.2.7 on 2026-07-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core', '0005_months_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sectors',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=20)),
                ('published_date', models.DateTimeField(auto_now=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
            },
        ),
    ]
