# Generated by Django 5.2.7 on 2026-07-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core', '0006_sectors'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=25, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Department Sections',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OfficeLocationPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('building', models.CharField(blank=True, max_length=150, null=True)),
                ('room', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
