# Generated by Django 5.2.7 on 2026-07-23 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "system_core",
            "0007_departmentsection_officelocationplacement",
        ),
        (
            "inventory",
            "0022_alter_inventoryitem_department_section_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OfficeLocationPlacement",
            new_name="OfficeLocation",
        ),
    ]