# Generated by Django 5.2.7 on 2026-07-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core', '0009_jobtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officelocation',
            name='building',
        ),
        migrations.RemoveField(
            model_name='officelocation',
            name='room',
        ),
        migrations.AddField(
            model_name='officelocation',
            name='floor',
            field=models.CharField(blank=True, choices=[('1', 'Ground Floor'), ('2', 'Second Floor'), ('3', 'Third Floor')], max_length=100, null=True),
        ),
    ]
