# Generated by Django 5.2.7 on 2026-02-05 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CAPAlerts',
            fields=[
                ('guid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('link', models.URLField(max_length=300)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=25)),
                ('pubdate', models.CharField(max_length=50)),
                ('is_published', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(auto_now=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'CAP Alert',
                'verbose_name_plural': 'CAP Alerts',
            },
        ),
        migrations.CreateModel(
            name='CAPAlertDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=30)),
                ('sent', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=25)),
                ('message_type', models.CharField(max_length=25)),
                ('scope', models.CharField(max_length=25)),
                ('language', models.CharField(max_length=5)),
                ('category', models.CharField(max_length=10)),
                ('event', models.CharField(max_length=50)),
                ('response_type', models.CharField(max_length=20)),
                ('severity', models.CharField(max_length=20)),
                ('certainty', models.CharField(max_length=20)),
                ('event_code', models.CharField(max_length=50)),
                ('value_name', models.CharField(max_length=15)),
                ('value', models.CharField(max_length=10)),
                ('onset', models.CharField(max_length=50)),
                ('expires', models.CharField(max_length=50)),
                ('sender_name', models.CharField(max_length=30)),
                ('headline', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('instruction', models.TextField()),
                ('area', models.CharField(max_length=30)),
                ('area_description', models.CharField(max_length=30)),
                ('polygon', models.TextField()),
                ('published_date', models.DateTimeField(auto_now=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('identifier', models.ForeignKey(db_column='identifier', on_delete=django.db.models.deletion.CASCADE, to='alerts.capalerts')),
            ],
            options={
                'verbose_name': 'CAP Alert Details',
                'verbose_name_plural': 'CAP Alert Details',
            },
        ),
    ]
