# Generated by Django 5.2.7 on 2026-02-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capalerts',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
