# Generated by Django 5.2.7 on 2026-02-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_capalerts_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capalertdetails',
            name='sender',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='capalerts',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
