# Generated by Django 5.2.7 on 2026-08-12 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alter_capalertdetails_sent_alter_capalerts_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='capalerts',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='capalertdetails',
            name='identifier',
            field=models.ForeignKey(db_column='identifier', on_delete=django.db.models.deletion.CASCADE, to='alerts.capalerts', to_field='guid'),
        ),
        migrations.AlterField(
            model_name='capalerts',
            name='guid',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
