# Generated by Django 5.2.7 on 2026-08-12 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_capalerts_id_alter_capalertdetails_identifier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TropicalWeatherAlerts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('storm_name', models.CharField(max_length=25)),
                ('storm_category', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tropical_alerts_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tropical_alerts_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tropical Weather Alerts',
                'verbose_name_plural': 'Tropical Weather Alerts',
            },
        ),
    ]
