# Generated by Django 5.2.7 on 2026-08-12 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_tropicalweatheralertscategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tropicalweatheralertscategory',
            old_name='description',
            new_name='category_name',
        ),
    ]
