# Generated by Django 5.2.7 on 2026-08-12 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0008_rename_description_tropicalweatheralertscategory_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tropicalweatheralerts',
            name='storm_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='probability_temp_max', to='alerts.tropicalweatheralertscategory'),
        ),
    ]
