# Generated by Django 5.2.7 on 2026-08-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_alter_tropicalweatheralerts_storm_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tropicalweatheralerts',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
