# Generated by Django 5.2.7 on 2026-08-12 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0010_alter_tropicalweatheralerts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tropicalweatheralerts',
            name='storm_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tropical_alerts_storm_category', to='alerts.tropicalweatheralertscategory'),
        ),
    ]
