# Generated by Django 5.2.7 on 2026-08-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0011_alter_tropicalweatheralerts_storm_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='capalertdetails',
            name='urgency',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
