# Generated by Django 5.2.7 on 2026-08-13 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0012_capalertdetails_urgency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capalertdetails',
            name='area',
        ),
    ]
