# Generated by Django 5.2.7 on 2026-08-13 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0013_remove_capalertdetails_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capalertdetails',
            old_name='value',
            new_name='event_code_value',
        ),
        migrations.RenameField(
            model_name='capalertdetails',
            old_name='value_name',
            new_name='event_code_value_name',
        ),
    ]
