# Generated by Django 5.2.7 on 2026-08-13 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0014_rename_value_capalertdetails_event_code_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capalertdetails',
            name='identifier',
            field=models.ForeignKey(db_column='identifier', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='alerts.capalerts', to_field='guid'),
        ),
    ]
