# Generated by Django 5.2.7 on 2026-08-13 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0015_alter_capalertdetails_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capalertdetails',
            name='event_code',
        ),
    ]
