# Generated by Django 5.2.7 on 2026-09-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0016_remove_capalertdetails_event_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capalertdetails',
            name='expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='capalerts',
            name='pubdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
